### ISSUE TITLE
Add Last month/week/today

### ISSUE THREAD

**Issue by SajadJalilian** [SamadiPour/rial-exchange-rates-archive#2]
If we add Last month/week/today, users of this repo can download total data once, and after that, they can use the latest data added and update their database.

**Comment by SamadiPour** [comment]
Since it’s history, there is no data for “Today”. You can still calculate the date for yesterday and get it directly from the repo.
But `last month` and `last week` are actually helpful and can be in the release section (since they will constantly change, and I don’t want them to affect git history)
