### ISSUE TITLE
Change daily update time

### ISSUE THREAD

**Issue by AlirezaMoVali** [SamadiPour/rial-exchange-rates-archive#7]
Hey Amir Hossein
First of all, thanks for your work on this repo. It been quite helpful in our projects.
I have a suggestion on time of adding daily conversion rates. Based on commit times, new rates for yesterday exchanges usually added around 4:40 to 4:50 am which is around 8:10 to 8:20 am in Iran's time zone. It would be appreciated if you could move it a little bit forward for adding it before 8 am in Iran's time zone. This comes from my experience in action of our calculations and work loads typically starts around 8 am.

Thanks

**Comment by SamadiPour** [comment]
If you [check here](https://github.com/SamadiPour/rial-exchange-rates-archive/blob/23101829af7dda6b6993f3b0ade58a76cba3773c/.github/workflows/daily_update.yml#L5) you'll see that the GitHub action is scheduled for 00:00 UTC. However, due to likely server load, it typically runs between 01:10 and 01:40 UTC. This means it is usually updated around 5:00 GMT (Iran's timezone).
